### ISSUE TITLE
Can not build on macOS with swift 3.0.2

### ISSUE THREAD

**Issue by zloidemon** [tris-foundation/messagepack#1]
```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

```
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                               ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:54: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                                                     ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                               ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:54: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                                                     ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                               ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:54: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                                                     ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                               ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:54: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                                                     ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                               ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:54: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                                                     ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:156:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == MessagePack {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:147:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == UInt8 {
                              ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                               ^
/Users/vg/Devel/Tarantool/Swift/messagepack/Sources/MessagePack+Initializable.swift:165:54: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == MessagePack, Value == MessagePack {
                                                     ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/vg/Devel/Tarantool/Swift/messagepack/.build/debug.yaml
```

**Comment by tonyfreeman** [comment]
Should have been closed with the others.
